Table cliente {
	id_cliente integer [ pk, increment, not null, unique ]
	nombre varchar
	apellido varchar
	telefono varchar
	id_cafe integer [ not null ]
}

Table empleado {
	id_emp integer [ pk, increment, not null, unique ]
	nombre varchar
	apellido varchar
	telefono varchar
	id_cliente integer [ not null ]
}

Table pastel {
	id_pastel integer [ pk, increment, not null, unique ]
	colores varchar
	pisos  varchar
	kilos varchar
	id_ent integer [ not null ]
}

Table entrega {
	id_ent integer [ pk, increment, not null, unique ]
	fecha varchar
	hora time
	orden decimal
	id_reciboi integer [ not null ]
}

Table recibo {
	id_rec integer [ pk, increment, not null, unique ]
	ruc varchar
	telefono integer
	precio decimal
}

Table cafe {
	id_cafe integer [ pk, increment, not null, unique ]
	Espresso varchar
	Latte varchar
	Cappuccino varchar
	Americano varchar
	id_pastel integer [ not null ]
}

Ref fk_pastel_id_ent_entrega {
	pastel.id_ent < entrega.id_ent [ delete: restrict, update: cascade ]
}

Ref fk_entrega_id_reciboi_recibo {
	entrega.id_reciboi < recibo.id_rec [ delete: restrict, update: cascade ]
}

Ref fk_empleado_id_cliente_cliente {
	empleado.id_cliente < cliente.id_cliente [ delete: restrict, update: cascade ]
}

Ref fk_cliente_id_cafe_cafe {
	cliente.id_cafe < cafe.id_cafe [ delete: restrict, update: cascade ]
}

Ref fk_cafe_id_pastel_pastel {
	cafe.id_pastel < pastel.id_pastel [ delete: restrict, update: cascade ]
}